### ISSUE TITLE
Using Simulink.Matlab only

### ISSUE THREAD

**Issue by rehan481** [ROV-Simulator/ROV-Simulator#1]
Hi,

Thank you for the invaluable BlueROV2 simulator, and I truly commend the efforts put into creating it.

My project revolves around designing and testing low-level controllers such as PID and SMC. To streamline this process, I am interested in simulating the modeling equations exclusively using MATLAB code or Simulink. Does your provided package support simulation with MATLAB code and Simulink alone?

Thank you for your time and assistance.
Ahmed.

**Comment by EsbenAAU** [comment]
As of today you need the Simulink 3D addon in order to run the simulator. Otherwise you should be able to run the simulator with only MATLAB and Simulink.
